### ISSUE TITLE
Allow maximumExposedStackSize minimum value to be set as low as 1

### ISSUE THREAD

**Issue by doofus9341** [pkmnfrk/equivalentintegrations#14]
The build released today fixed a lot of the freezing problems previous releases had, however extracting items with high EMC values causes a lot of item updates in the Refined Storage system which can freeze the client for long periods of time. In larger modpacks this can cause the client to freeze for several seconds or several minutes depending on the number of updates. The option to allow setting maximumExposedStackSize as low as 1 to skip the majority of item updates would be a great feature. Equivalent Energistics will only display one of each EMCable item but still allows you to craft/extract a stack of the item. You could optionally add a small counter to display the users EMC in the UI or possibly in the form of a block to allow users to still have some idea of how much EMC they posses.

**Comment by pkmnfrk** [comment]
I get where you're coming from, but I don't think that's a good idea. Setting it to 1 would severely limit auto crafting, and it would, in fact, limit you to extracting a single item at a time. Even the current minimum of 64 would be a nightmare to work with, in practise. It's not really a good idea to compare to the Transmutation Table, since that UI is part of ProjectE and understands what's really going on. Refined Storage... does not.

As I explained in #12, this problem is on Refined Storage's end, and has been encountered by other mods as well. It is just that the functionality of this mod seems to be specifically tailored to triggering it as much as possible.

I'm going to say that we should keep any further discussion of Refined Storage x this mod in that bug.

(By the way, the extra UI or block to view your EMC is the Transmutation Table/Tablet from ProjectE)

**Comment by pkmnfrk** [comment]
FYI, this has been fixed in Refined Storage, as of this build:

https://jenkins.raoulvdberge.com/job/refinedstorage/283/
