### ISSUE TITLE
Pressing "x" button on Refined Storage Crafting Grid to put items back into system locks up game indefinitely

### ISSUE THREAD

**Issue by jakerist** [pkmnfrk/equivalentintegrations#17]

**Comment by pkmnfrk** [comment]
I'm afraid I'm going to need more details. Assuming you are running the latest version of Equivalent Integrations, what version of Refined Storage are you running? How is your Transmutation Chamber set up? Does it happen all the time, or just occasionally?

**Comment by pkmnfrk** [comment]
I just tested myself with the latest release (1.6.5) and the latest dev version of Refined Storage, and neither one seemed to exhibit the symptoms. In addition to the questions I asked above, can you post a Minecraft log (using gist.github.com)?

**Comment by jakerist** [comment]
im running the latest version of both mods, transmutation chamber is setup with an external storage, happens every time i press the 'x' button to move items back into the storage system from the crafting grid. 

minecraft latest log: https://gist.github.com/jakerist/f2221398d9acb1dd8a3e89bd6328e543
minecraft debug log: https://gist.github.com/jakerist/b9ea5086547e0d1cd58caff3ff1a9090

could it potentially be an issue with inventory sorter?

**Comment by pkmnfrk** [comment]
Interesting, it definitely seems like inventorysorter might be related. Let me see if I can reproduce with that.

**Comment by pkmnfrk** [comment]
Hmm. Just adding inventory sorter doesn't seem to change anything...

Judging by your log, I'm assuming you're running StoneBlock? Let me try reproducing it there...

**Comment by pkmnfrk** [comment]
Sigh, I really cannot get this to reproduce. I saw the same debug lines about inventory sorter as you, but it didn't seem to affect game play.

One possibility is that our computers are of different performance profiles. Are you running on a "gaming" pc, or a laptop, or something else? Do you normally get 60 FPS in StoneBlock? If you don't, then it's possible this is the issue, and I can't see it because my computer just powers through (although, if it were locking up completely, I should still expect that to happen, so I dunno)

I also noticed our mod lists were different. I think you're running a slightly older version of StoneBlock, and I think you also added Equivalent Storage. I tested with the latter (even hooking it up to the RS system), but it didn't help.

If there are any other mods you added, or any other configurations you changed, please let me know so I can try adding them too.

Other than that, the only thing I can suggest is that you try updating StoneBlock itself, and see if the problem persists. If it does, then the only other recourse I can think of is for you to zip up your entire profile folder, with mods, worlds and configs, and upload it somewhere so I can inspect it directly.

**Comment by jakerist** [comment]
I get 400-500 fps on stoneblock so thats not the issue
my stoneblock profile: https://mega.nz/#!hJFiECLC!rukS-OE6OP8v1ESkekKaSleJd2d2haSl-qGzH7jBUc8

**Comment by pkmnfrk** [comment]
Well shucks, I only get 300 fps on your profile (less when recording).

Anyway, at this point it's probably not surprising, but I still cannot reproduce it :(

Just in case there is a misunderstanding of what the bug is, here's a clip of me trying to reproduce the issue:

https://youtu.be/EVAHI8uMILg

Assuming this is correct, then... man, I dunno.

**Comment by pkmnfrk** [comment]
OK, last try to at least confirm that this has anything to do with Equivalent Integrations.

If you replace the mod with this file, it should output some debug data into latest.log:

[EquivalentIntegrations-0.1.8-debug-PE1.3.1B.jar.zip](https://github.com/pkmnfrk/equivalentintegrations/files/2479990/EquivalentIntegrations-0.1.8-debug-PE1.3.1B.jar.zip)

Normal operations should look like this:

```
[14:08:22] [Server thread/INFO] [equivalentintegrations]: Materializing a stack (32xtile.stainedGlass@0) for 1 EMC each, a total of 32 (Simulation: true)
[14:08:22] [Server thread/INFO] [equivalentintegrations]: Done materializing said stack
[14:08:22] [Server thread/INFO] [equivalentintegrations]: Materializing a stack (32xtile.stainedGlass@0) for 1 EMC each, a total of 32 (Simulation: false)
[14:08:22] [Server thread/INFO] [equivalentintegrations]: Done materializing said stack
[14:08:22] [main/INFO] [projecte]: ** RECEIVED TRANSMUTATION DATA CLIENTSIDE **
[14:08:24] [Server thread/INFO] [equivalentintegrations]: Burning a stack (31xtile.stainedGlass@0) for 1 EMC each, a total of 31 (Simulation: false)
[14:08:24] [Server thread/INFO] [equivalentintegrations]: Done burning said stack
[14:08:25] [main/INFO] [projecte]: ** RECEIVED TRANSMUTATION DATA CLIENTSIDE **
[14:08:38] [Server thread/INFO] [equivalentintegrations]: Burning a stack (1xtile.stainedGlass@0) for 1 EMC each, a total of 1 (Simulation: false)
[14:08:38] [Server thread/INFO] [equivalentintegrations]: Done burning said stack
[14:08:38] [main/INFO] [projecte]: ** RECEIVED TRANSMUTATION DATA CLIENTSIDE **
```

This represents me taking a stack (32) of stained glass out of my inventory, putting one on the crafting grid, putting the other 31 back into the inventory, and then pressing the X button.

If it doesn't look like that (eg, it cuts off before the "Done" line, or there are a lot more lines than expected), then there might be a problem.

**Comment by pkmnfrk** [comment]
I'm going to assume that this is no longer a problem.
