### ISSUE TITLE
server crash loop

### ISSUE THREAD

**Issue by preceptor-teeth** [pkmnfrk/equivalentintegrations#20]
The server seems to be stuck in a crash loop.  Here is a sample of one of the crash-logs:

https://pastebin.com/fUKjD2Dp

Any ideas on how to resolve this?

**Comment by pkmnfrk** [comment]
I'm assuming that as soon as you boot the server, it bombs again? Hm.

It seems like it's crashing while inserting items into an offline player's EMC store. Or, more specifically, it's crashing while trying to check whether that player already knows that item. Which really shouldn't blow up.

Is this the first crash, or a subsequent crash? If you have the earliest crash report, that might be useful to look at to pinpoint the real cause. I doubt that it's caused by Equivalent Integrations directly, but it might have some clues.

In the mean time, I recommend disabling EI temporarily. You'll get a warning from Forge about missing block ids that you'll have to resolve by typing a command into the server console directly, but at least you'll be able to play again.

**Comment by pkmnfrk** [comment]
I looked at the place it's crashing in Project E, and it doesn't really make sense. As I mentioned, it's crashing while looking up whether a player knows a thing or not, which should be very fast. 

I honestly have no idea what might be causing this. I think I need to ask you to zip up your server folder (excluding logs, but including the world folder) and upload it to Google Drive or something so I can debug it further.

**Comment by preceptor-teeth** [comment]
So I ended up restoring from backup, and the problem went away and hasn't come back.  Sorry for the lack of followup.

**Comment by pkmnfrk** [comment]
Hmm, ok, but if it happens again, please let me try and look at it.
