### ISSUE TITLE
The real amount of items is not shown properly.

### ISSUE THREAD

**Issue by jk1895** [pkmnfrk/equivalentintegrations#30]
The real amount of items is not shown properly.

I don't know if this is a bug and if it' the "fault" of EI.
What I noticed is this:

AE2 shows just 14 items (which have lots of EMC):
https://imgur.com/a/IF1rlan
But the real amount is much bigger (shown in the new Project Ex tablet):
https://imgur.com/a/RLN2dJQ

It would be cool to see the real number in my AE2 system. Maybe you could look over this.
Thanks a lot (specially for the great mod!)

**Comment by pkmnfrk** [comment]
Hm. I have a theory, though it is purely guessing, since I've not played with Project-EX. My assumption is that the item in question is extremely expensive, yes? And although you have a very large amount of EMC, I think the math is just too big. I think that EI sees your EMC (approximately 1.1 x 10<sup>21</sup>) and truncates it to a 64-bit integer (approximately 9 x 10<sup>18</sup>), and does the math from there.

Can you confirm the EMC value of that item? If that value x 15 is greater than 9,223,372,036,854,775,808, then that is the case.

I'll look into this issue, though I can't guarantee that I can fix this in a satisfactory manner.

**Comment by jk1895** [comment]
Thanks for the fast response.
Yes, the item "The Final Star" has a lot EMC but less then 9,223,372,036,854,775,808: https://imgur.com/a/04PaElS
My EMC value is by now: https://imgur.com/a/ZLeXPSx
That's enough for ~4700 final stars.

Yeah, the numbers gets went a bit crazy but I like it :)

**Comment by pkmnfrk** [comment]
OK, actually this was easy to fix. There is still an issue where the number might be off by one in cases of very large numbers (like in this case), but it will at least be very close.

I'll make a release shortly.
