### ISSUE TITLE
Crash when trying to use JEI + to fill the crafting window.

### ISSUE THREAD

**Issue by Seyeght** [pkmnfrk/equivalentintegrations#8]
Forge: 1.12.2-14.23.4.2747
Equivalent Integrations: 0.1.4

This crash happens both when hitting the plus symbol to populate the items, or when trying to remove the final product from the crafting window.

Crash report: https://pastebin.com/vTnFeHsC

**Comment by Seyeght** [comment]
I should note, this is on a server, and we both have our tablets connected to the same AE2 system.

**Comment by pkmnfrk** [comment]
So, I'm assuming you're talking about crafting via AE2, as in with a Crafting Terminal or similar?

**Comment by pkmnfrk** [comment]
I'm assuming you have a fairly active AE system in order to hit this. It requires the server to be interacting with your inventory automatically (auto crafting job, import/export bus, etc) and manually triggered (via a GUI of some kind) at exactly the same time. It's pretty rare, and I wasn't able to reproduce it myself.

However, I (am pretty sure I) fixed it. Please try [this build](https://github.com/pkmnfrk/equivalentintegrations/releases/tag/v0.1.5) out, see if it works out better for you.

**Comment by Seyeght** [comment]
We actually dont have a very active AE system, but I could give you video examples of what was happening during the crash, I am 100% positive it was because it was on a server and both players had their table/tablets connected to the same AE network, both knowing different items. 
Once we removed one of our Transmutation Chamber the server stopped crashing when trying to manually craft things.
1st crash: https://clips.twitch.tv/ArbitraryGlamorousDotterelDerp
2nd crash: https://clips.twitch.tv/ExuberantProductiveTurtleRuleFive

There were numerous other crashes, but most of them were when I was crafting and not when he was, so there wasnt a recording on those.

We will try the update you suggested.

**Comment by pkmnfrk** [comment]
Ohh, I misunderstood, you had two different Transmutation Chambers... I see, I did not try that. In principle, this should fix that anyway, but I'll try it out just in case.

**Comment by pkmnfrk** [comment]
Whoops, you are correct, it crashes immediately in this case! Fun times, let me see what I can do

**Comment by pkmnfrk** [comment]
Ok, fixed for real this time in 0.1.5 (https://github.com/pkmnfrk/equivalentintegrations/releases/tag/v0.1.5)
